# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 928e851eed931c0caa00bcff6cc116917c077aa421ef8b60999c7d4a8ff6460f6bc651a1a6da1b81dddcc97b0789dc7144bc5d9ae58da7b3ecff97785fd581f0

test:
  secret_key_base: e250fb704a450bd58f0ec2490936f42e0de934cc49900bef44db02555e289005cb0e42df2693f2d061390fed4a1ea1197056c65e934b3426165e2023ee3c38f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
